define({
  "_widgetLabel": "Zoznam vrstiev",
  "titleBasemap": "Základné mapy",
  "titleLayers": "Operačné vrstvy",
  "labelLayer": "Názov vrstvy",
  "itemZoomTo": "Priblížiť na",
  "itemTransparency": "Priehľadnosť",
  "itemSetVisibilityRange": "Nastavte rozsah viditeľnosti",
  "itemTransparent": "priehľadný",
  "itemOpaque": "nepriehľadný",
  "itemMoveUp": "Posunúť hore",
  "itemMoveDown": "Posunúť dolu",
  "itemDesc": "Opis",
  "itemDownload": "Stiahnuť",
  "itemToAttributeTable": "Zobraziť v tabuľke atribútov",
  "itemShowItemDetails": "Zobraziť podrobnosti o položke",
  "empty": "prázdne",
  "removePopup": "Zakázať kontextové okno",
  "enablePopup": "Povoliť kontextové okno",
  "turnAllLayersOff": "Vypnúť všetky vrstvy",
  "turnAllLayersOn": "Zapnúť všetky vrstvy",
  "expandAllLayers": "Rozbaliť všetky vrstvy",
  "collapseAlllayers": "Zbaliť všetky vrstvy",
  "turnAllLabelsOff": "Vypnúť všetky označenia",
  "turnAllLabelsOn": "Zapnúť všetky označenia",
  "showLabels": "Zobraziť označenia",
  "hideLables": "Skryť označenia",
  "keyword": "Kľúčové slovo",
  "basemapLayers": "Vrstvy základnej mapy",
  "typeAKeywork": "Napíšte kľúčové slovo",
  "layers": "Vrstvy",
  "tipLayerSearch": "Vyhľadať vrstvy",
  "tipLayerListOperation": "Operácie zoznamu vrstiev",
  "tipLayerOperation": "Menu vrstiev",
  "tipClearText": "Vymazať text",
  "collapseLayer": "Zbaliť",
  "expandLayer": "Rozbaliť"
});