define({
  "_widgetLabel": "Списък със слоеве",
  "titleBasemap": "Базови карти",
  "titleLayers": "Оперативни слоеве",
  "labelLayer": "Име на слой",
  "itemZoomTo": "Приближаване",
  "itemTransparency": "Прозрачност",
  "itemSetVisibilityRange": "Настройване на диапазон на видимост",
  "itemTransparent": "Прозрачно",
  "itemOpaque": "Непрозрачно",
  "itemMoveUp": "Нагоре",
  "itemMoveDown": "Надолу",
  "itemDesc": "Описание",
  "itemDownload": "Изтегляне",
  "itemToAttributeTable": "Преглед в таблицата с атрибути",
  "itemShowItemDetails": "Показване на подробна информация за елемент",
  "empty": "празно",
  "removePopup": "Деактивиране на изскачащи прозорци",
  "enablePopup": "Активиране на изскачащи прозорци",
  "turnAllLayersOff": "Изключване на всички слоеве",
  "turnAllLayersOn": "Включване на всички слоеве",
  "expandAllLayers": "Разгъване на всички слоеве",
  "collapseAlllayers": "Сгъване на всички слоеве",
  "turnAllLabelsOff": "Изключване на всички надписи",
  "turnAllLabelsOn": "Включване на всички надписи",
  "showLabels": "Показване на надписи",
  "hideLables": "Скриване на надписи",
  "keyword": "Ключова дума",
  "basemapLayers": "Слоеве на базова карта",
  "typeAKeywork": "Изпишете ключова дума",
  "layers": "Слоеве",
  "tipLayerSearch": "Слоеве за търсене",
  "tipLayerListOperation": "Операции със списъка на слоевете",
  "tipLayerOperation": "Менюта за слой",
  "tipClearText": "Изчистване на текста",
  "collapseLayer": "Сгъване",
  "expandLayer": "Разгъване"
});